apiVersion: v1
kind: Service
metadata:
  name: {{ include "infosys.fullname" . }}
  labels:
    app: rai-mmodel
    version: v1
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.infosys }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: rai-mmodel
    version: v1
