apiVersion: v1
kind: Service
metadata:
  name: {{ include "infosys.fullname" . }}
  labels:
    app: rai-mmodel
    version: v1
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: infosys
      port: {{ .Values.service.ports.infosys }}
      targetPort: infosys
      protocol: TCP
  selector:
    app: rai-mmodel
    version: v1
